StackExchange = window.StackExchange || {};
StackExchange.Unikong = StackExchange.Unikong || {};

StackExchange.Unikong.Boot = function () { };
StackExchange.Unikong.Preload = function () { };

StackExchange.Unikong.Preload.prototype = {
    preload: function () {
        var progressBar = this.add.sprite(this.game.world.centerX, this.game.world.centerY, 'progress');
        progressBar.anchor.setTo(0.5);
        this.load.setPreloadSprite(progressBar);

        this.load.image('menu-bg', 'img/unikong/welcome-bg.png');
        this.load.spritesheet('btn-new', 'img/unikong/btn-new.png', 380, 60);
        this.load.spritesheet('btn-exit', 'img/unikong/btn-exit.png', 380, 60);
        this.load.spritesheet('btn-credits', 'img/unikong/btn-credits.png', 380, 60);
        this.load.spritesheet('btn-leaderboard', 'img/unikong/btn-leaderboard.png', 380, 60);
        this.load.spritesheet('btn-resume', 'img/unikong/btn-resume.png', 380, 60);
        this.load.spritesheet('btn-restart', 'img/unikong/btn-restart.png', 380, 60);
        this.load.spritesheet('btn-return', 'img/unikong/btn-return.png', 380, 60);
        this.load.spritesheet('btn-continue', 'img/unikong/btn-continue.png', 380, 60);

        this.load.spritesheet('player', 'img/unikong/player.png', 40, 68);
        this.load.spritesheet('player-armed', 'img/unikong/player-armed.png', 42, 68);
        this.load.spritesheet('boss', 'img/unikong/unicorn.png', 86, 84);
        
        this.load.image('bg', 'img/unikong/bg.png');
        this.load.image('win-bg', 'img/unikong/win-bg.png');
        this.load.image('game-over-bg', 'img/unikong/game-over-bg.png');
        this.load.image('scores-bg', 'img/unikong/scores-bg.png');
        this.load.image('credits', 'img/unikong/credits.png?v=1337');

        this.load.image('platform', 'img/unikong/steel.png'); // 60 x 41
        this.load.image('ground', 'img/unikong/brick.png');
        this.load.image('diamond', 'img/unikong/gem.png');
        this.load.image('diamondParticle', 'img/unikong/gem-particle.png');

        this.load.image('ladder', 'img/unikong/ladder.png');

        this.load.image('sound-on', 'img/unikong/sound-on.png');
        this.load.image('sound-off', 'img/unikong/sound-off.png');

        this.load.spritesheet('downvote', 'img/unikong/downvote-torch.png', 34, 77);


        this.load.image('bigGold', 'img/unikong/gold-big.png');
        this.load.image('bigSilver', 'img/unikong/silver-big.png');
        this.load.image('bigBronze', 'img/unikong/bronze-big.png');

        this.load.image('gold', 'img/unikong/gold.png');
        this.load.image('silver', 'img/unikong/silver.png');
        this.load.image('bronze', 'img/unikong/bronze.png');
        
        this.load.image('goldParticle', 'img/unikong/gold-particle.png');
        this.load.image('silverParticle', 'img/unikong/silver-particle.png');
        this.load.image('bronzeParticle', 'img/unikong/bronze-particle.png');

        this.load.image('heart', 'img/unikong/heart.png');

        this.load.spritesheet('rainbow', 'img/unikong/rainbow.png', 49, 20);
        this.load.image('laser', 'img/unikong/laser.png');
        this.load.spritesheet('troll', 'img/unikong/troll.png', 48, 54);
        this.load.image('chest-open', 'img/unikong/chest-open.png');
        this.load.image('chest-closed', 'img/unikong/chest-closed.png');
        this.load.image('key', 'img/unikong/key.png');

        // generated by http://www.bfxr.net/
        this.load.audio('jump', 'img/unikong/jump.mp3');
        this.load.audio('death', 'img/unikong/death.mp3');
        this.load.audio('pickup', 'img/unikong/pickup.mp3');
        this.load.audio('pickup-badge', 'img/unikong/pickup-badge.mp3');
        this.load.audio('shoot', 'img/unikong/shoot.mp3');

        this.load.audio('theme', 'img/unikong/music.mp3');
        this.load.audio('gameOverIntro', 'img/unikong/game-over-intro.mp3');
        this.load.audio('gameOverTheme', 'img/unikong/game-over-music.mp3');
        this.load.audio('winTheme', 'img/unikong/win.mp3');
        this.load.audio('lossTheme', 'img/unikong/lose.mp3');

        this.load.image('font', 'img/unikong/joystix_monospace_white2.png');
    },
    create: function() {
        this.state.start('Menu');
    }
};


StackExchange.Unikong.Boot.prototype = {
    preload: function () {
        StackExchange.Unikong.game.load.baseURL = window.baseUrl;
        StackExchange.Unikong.game.load.crossOrigin = 'anonymous';

        this.load.image('progress', 'img/unikong/load-progress.png');
    },
    create: function () {
        this.state.start('Preload');

        StackExchange.Unikong.game.input.keyboard.onDownCallback = function (key) {
            StackExchange.Unikong.checkKonamiKey(key);
        }
    }
};